# No services defined - MCP Inspector now runs directly via npm script
# Use: npm run mcp:inspector to start MCP Inspector
# This eliminates Docker vulnerabilities and simplifies the setup

# Future services can be added here as needed
services: {}
